---
title: 'Comparing the Amount of Water Needed to Produce Different Foods '
author: 'Sancho '
date: '2020-03-01'
slug: water-needed-to-produce-food
categories: []
tags:
  - Food
  - Environmental
subtitle: ''
summary: ''
authors: []
lastmod: '2020-03-01T19:49:32-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
output:
  blogdown::html_page:
    toc: yes
draft: true
---

```{r include=FALSE, eval=FALSE}
# render magic (copied from ellocke, not exactly sure what this does)
rmarkdown::render("index.Rmd")
```

```{r}
#links
#https://www.naturalearthdata.com/downloads/10m-physical-vectors/10m-lakes/
#https://waterfootprint.org/en/resources/waterstat/product-water-footprint-statistics/


```

#Why should we care about water? 

I remember my first reaction to hearing about water scarcity was doubt. I mean isn't 70% of the whole planet covered in water? How can we possibly have a problem. Then, in January of 2019 it was announced that Cape Town, SOuth

##Fresh Water Scarcity 


```{r}
library(ggplot2)
library(dplyr)
library(maps)


```
